#!/usr/bin/env node
// Exports all legacy v1 (SJCL) pastes from a PrivateBin Filesystem `data/`
// directory into static JSON blobs for the read-only archive viewer.
//
//   node export.js /path/to/privatebin/data
//
// Writes:  p/<id>.json                one file per v1 paste  {f,d,t}
//          v1-ids.txt                 newline list of exported paste ids
//          paste-v1-redirect.caddy    Caddy map snippet for the old host

const fs = require('fs');
const path = require('path');

const dataDir = process.argv[2];
const outDir = __dirname;
if (!dataDir || !fs.existsSync(dataDir)) {
  console.error('usage: node export.js /path/to/privatebin/data');
  process.exit(1);
}

const pDir = path.join(outDir, 'p');
fs.mkdirSync(pDir, { recursive: true });

const isPasteId = (name) => /^[0-9a-f]{16}\.php$/.test(name);

function* walk(dir) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) yield* walk(full);
    else if (isPasteId(e.name)) yield full;
  }
}

let v1 = 0, v2 = 0, skipped = 0;
const ids = [];
const modes = { gcm: 0, ccm: 0, alpha: 0 };

for (const file of walk(dataDir)) {
  const id = path.basename(file, '.php');
  let raw;
  try { raw = fs.readFileSync(file, 'utf8'); }
  catch { console.warn('unreadable:', file); skipped++; continue; }

  const s = raw.indexOf('{'), e = raw.lastIndexOf('}');
  if (s < 0 || e < 0) { skipped++; continue; }
  let outer;
  try { outer = JSON.parse(raw.slice(s, e + 1)); } catch { skipped++; continue; }

  // v2 pastes (WebCrypto, adata array) still work in PrivateBin 2.x -> skip
  if (Array.isArray(outer.adata)) { v2++; continue; }
  if (typeof outer.data !== 'string') { skipped++; continue; }

  const meta = outer.meta || {};
  const formatter = meta.formatter || 'plaintext';
  const postdate = meta.postdate || meta.created || 0;

  // classify SJCL mode for reporting
  let mode = 'alpha';
  const m = /"mode"\s*:\s*"(\w+)"/.exec(outer.data);
  if (m) mode = m[1];
  modes[mode] = (modes[mode] || 0) + 1;

  fs.writeFileSync(
    path.join(pDir, id + '.json'),
    JSON.stringify({ f: formatter, t: postdate, d: outer.data })
  );
  ids.push(id);
  v1++;
}

ids.sort();
fs.writeFileSync(path.join(outDir, 'v1-ids.txt'), ids.join('\n') + '\n');

// Caddy map snippet: query (raw paste id) -> "1" for known v1 pastes
const mapLines = ids.map((id) => `\t${id} 1`).join('\n');
fs.writeFileSync(
  path.join(outDir, 'paste-v1-redirect.caddy'),
  `# generated by export.js - import into the paste.example.com vhost\n` +
  `map {query} {is_legacy_v1} {\n\tdefault 0\n${mapLines}\n}\n` +
  `@legacy_v1 expression {is_legacy_v1} == "1"\n` +
  `redir @legacy_v1 https://old.paste.example.com/?{query} 301\n`
);

console.log(`v1 exported: ${v1}  (gcm=${modes.gcm||0} ccm=${modes.ccm||0} alpha=${modes.alpha||0})`);
console.log(`v2 skipped (still work in 2.x): ${v2}`);
console.log(`unusable skipped: ${skipped}`);
console.log(`-> p/*.json, v1-ids.txt, paste-v1-redirect.caddy`);
